server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdb?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor
    username: root
    password: root
    tomcat:
      jdbc-interceptors: com.amazonaws.xray.sql.mysql.TracingInterceptor
